### ISSUE TITLE
I think the notifications disable event listener is missing...

### ISSUE THREAD

**Issue by june07** [june07/nimv3#6]

**Comment by june07** [comment]
nope

**Comment by l-Nuril-l** [comment]
Why does V3, on every file change, close and reopen the page instead of just reloading it, and also cause the browser to flash orange? This is a bit annoying, which is why I'm currently using V2.

**Comment by june07** [comment]
Did you try to toggle the UI settings, "Close Automatically."

![image](https://github.com/june07/nimv3/assets/11353590/477b9fe1-5177-4813-b3a6-a200da54a612)

See if that resolves your issue, would help to see a screen capture of what you are experiencing otherwise so I can debug it better. Google is forcing the switch to V3 next month so that's why the push to NiMV3 is finally being done (was pushed out today actually).

You should still be able to side load V2 from github of course https://github.com/june07/nim, but I'd love to fix this if it is indeed a bug...

**Comment by l-Nuril-l** [comment]
https://github.com/june07/nimv3/assets/49325887/4a3685b7-0bae-4332-b4e4-daf0e3cf0f81

**Comment by june07** [comment]
Got it... well, at least I was able to duplicate the issue on my end. I don't use the windowed mode myself and you're the first to bring this up. I think I have an idea of what the problem is (the debugger protocol code might be ignoring the Close Automatically setting.  I'm gonna open another issue and work on getting this resolved asap (it's almost midnight here in Cali and I'm already a bit deep into a bottle at the moment... not to mention it's my bday (generally those things don't really matter, but I guess I thought it important to grab whatever excuse I could to put this off until tomorrow). Cheers, thanks for taking the time to provide the feedback, and hopefully we can get it resolved before the weekend is up!

**Comment by l-Nuril-l** [comment]
> it's my bday
Happy birthday! No rush on the fix; it's not critical. 🎉
