### ISSUE TITLE
Auto close settings is being ignored by the devtools protocol code.

### ISSUE THREAD

**Issue by june07** [june07/nimv3#7]
https://github.com/june07/nimv3/issues/6#issuecomment-2119126312

**Comment by june07** [comment]
@l-Nuril-l the newest version is 3.6.7 and it's available from the Chrome Webstore already, Edge is a little slower. Please confirm once you've tested it. Thanks.

**Comment by l-Nuril-l** [comment]
> Please confirm once you've tested it.

With the "Open in new window" option.
Now the page opens in my main browser, but when I edit the code, it just stops working.
If I close the tab the only way to open the page again is to restart the extension.
Also now the plugin version in the app doesn't match the real version.

**Comment by l-Nuril-l** [comment]
Already looks functional.
But there are some problems:
1. If you turn off "Make Windows Focused." everything breaks.
2. The application sometimes turns into a white screen.
2.1 ![image](https://github.com/june07/nimv3/assets/49325887/3b067ca2-62f8-4362-acc6-add5a2c220f9)
2.2 ![image](https://github.com/june07/nimv3/assets/49325887/4ad682be-0ea0-44e7-a84f-e8908f40bf91)

Is it a limitation of Manifest V3 that you open a new tab first instead of rebooting?

**Comment by june07** [comment]
1. The "Make Window Focused" issue has been resolved in the version I just pushed 3.6.10
2. I have noticed this myself and I have opened [a separate issue](https://github.com/june07/nimv3/issues/10) about this. I assume you mean the popup turns white/blank... and re-opening it (clicking the popup again) resolves the issue. I haven't yet been able to track down why this is happening.
3. I get what you're saying about this one, and to answer your question, it's not a limit of the API I don't think (not absolutely sure yet) but just the way it was done. I get that it causes a bit of an unpleasant UI/UX... and the update I just made (2.6.11) seems to be an acceptable fix...

Old way:
![nimv3-issues-7-beforeGroupFix](https://github.com/june07/nimv3/assets/11353590/38c25b05-90e4-4c7d-8d8b-e05f21fb689a)

New way:
![nimv3-issues-7-afterGroupFix](https://github.com/june07/nimv3/assets/11353590/e8a441c7-a759-4105-bf6f-3e8ada4aad0d)

What do you think about the difference?
I will say I spent a bit of time trying to match the behavior exactly, but it started to become a time sink.

And thanks for your continued feedback on this!

**Comment by l-Nuril-l** [comment]
> What do you think about the difference?

The old way is better as now the tab loses its position in ALT + TAB and opens at the very end.
In V2 version everything looks more correct, but actually I agree it's already prefectionism.

**Comment by l-Nuril-l** [comment]
Doesn't work after restarting the browser.
A simple fix is to open "Inspect" from the extension.
https://github.com/june07/nimv3/assets/49325887/2d50353c-db08-43a3-aa5d-fbffd90af6d1

**Comment by june07** [comment]
Thank you for the 5-star rating, much appreciated!

>Doesn't work after restarting the browser.

I watched your screen capture and I'm pretty sure you're referring to [this issue](https://blog.june07.com/chromium-bug-900945/) which has been ongoing! I've updated the install page to inform people about it and I wish Google would fix it because I'm sure a lot of folks thing NiM doesn't work and immediately de-install/dismiss.

**Comment by l-Nuril-l** [comment]
V2 RIP
![image](https://github.com/june07/nimv3/assets/49325887/e2c226ce-b2ce-4d0a-b9d8-86904ad0dceb)

> What do you think about the difference?

Please roll back to the old way. https://github.com/june07/nimv3/commit/9aa1bba0e6cce11272db45e5d64742f0b64e30d7 Thanks.

**Comment by june07** [comment]
https://github.com/june07/nimv3/releases/tag/v3.6.12

**Comment by l-Nuril-l** [comment]
> https://github.com/june07/nimv3/releases/tag/v3.6.12

Empty commit

**Comment by june07** [comment]
@l-Nuril-l I wanted to circle back around to this issue before closing it out to say thank you again for working with me on this issue. I wish more developers provided similar valuable feedback about their own workflows and usage of NiM. It helps a great deal in understanding how to make it better and how to fix things that I don't necessarily see in my own workflows.

Anyway, thank you again!

This specific issue is resolve so I'm closing this out. Still have an eye on the other one.
